/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.goodreturn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.goodreturn.model.Borrower;
import org.goodreturn.model.BorrowerModel;
import org.goodreturn.model.BorrowerSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Borrower service. Represents a row in the &quot;GoodReturn_Borrower&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.goodreturn.model.BorrowerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BorrowerImpl}.
 * </p>
 *
 * @author gilaa004
 * @see BorrowerImpl
 * @see org.goodreturn.model.Borrower
 * @see org.goodreturn.model.BorrowerModel
 * @generated
 */
@JSON(strict = true)
public class BorrowerModelImpl extends BaseModelImpl<Borrower>
	implements BorrowerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a borrower model instance should use the {@link org.goodreturn.model.Borrower} interface instead.
	 */
	public static final String TABLE_NAME = "GoodReturn_Borrower";
	public static final Object[][] TABLE_COLUMNS = {
			{ "borrower_Id", Types.BIGINT },
			{ "abacus_Person_Id", Types.BIGINT },
			{ "village", Types.VARCHAR },
			{ "district", Types.VARCHAR },
			{ "pdf_Link", Types.VARCHAR },
			{ "currency_", Types.DOUBLE },
			{ "changed_By", Types.VARCHAR },
			{ "changed_Time", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table GoodReturn_Borrower (borrower_Id LONG not null primary key,abacus_Person_Id LONG,village VARCHAR(75) null,district VARCHAR(75) null,pdf_Link VARCHAR(75) null,currency_ DOUBLE,changed_By VARCHAR(75) null,changed_Time LONG)";
	public static final String TABLE_SQL_DROP = "drop table GoodReturn_Borrower";
	public static final String ORDER_BY_JPQL = " ORDER BY borrower.borrower_Id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GoodReturn_Borrower.borrower_Id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.goodreturn.model.Borrower"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.goodreturn.model.Borrower"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Borrower toModel(BorrowerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Borrower model = new BorrowerImpl();

		model.setBorrower_Id(soapModel.getBorrower_Id());
		model.setAbacus_Person_Id(soapModel.getAbacus_Person_Id());
		model.setVillage(soapModel.getVillage());
		model.setDistrict(soapModel.getDistrict());
		model.setPdf_Link(soapModel.getPdf_Link());
		model.setCurrency(soapModel.getCurrency());
		model.setChanged_By(soapModel.getChanged_By());
		model.setChanged_Time(soapModel.getChanged_Time());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Borrower> toModels(BorrowerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Borrower> models = new ArrayList<Borrower>(soapModels.length);

		for (BorrowerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.goodreturn.model.Borrower"));

	public BorrowerModelImpl() {
	}

	public long getPrimaryKey() {
		return _borrower_Id;
	}

	public void setPrimaryKey(long primaryKey) {
		setBorrower_Id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_borrower_Id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Borrower.class;
	}

	public String getModelClassName() {
		return Borrower.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("borrower_Id", getBorrower_Id());
		attributes.put("abacus_Person_Id", getAbacus_Person_Id());
		attributes.put("village", getVillage());
		attributes.put("district", getDistrict());
		attributes.put("pdf_Link", getPdf_Link());
		attributes.put("currency", getCurrency());
		attributes.put("changed_By", getChanged_By());
		attributes.put("changed_Time", getChanged_Time());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long borrower_Id = (Long)attributes.get("borrower_Id");

		if (borrower_Id != null) {
			setBorrower_Id(borrower_Id);
		}

		Long abacus_Person_Id = (Long)attributes.get("abacus_Person_Id");

		if (abacus_Person_Id != null) {
			setAbacus_Person_Id(abacus_Person_Id);
		}

		String village = (String)attributes.get("village");

		if (village != null) {
			setVillage(village);
		}

		String district = (String)attributes.get("district");

		if (district != null) {
			setDistrict(district);
		}

		String pdf_Link = (String)attributes.get("pdf_Link");

		if (pdf_Link != null) {
			setPdf_Link(pdf_Link);
		}

		Double currency = (Double)attributes.get("currency");

		if (currency != null) {
			setCurrency(currency);
		}

		String changed_By = (String)attributes.get("changed_By");

		if (changed_By != null) {
			setChanged_By(changed_By);
		}

		Long changed_Time = (Long)attributes.get("changed_Time");

		if (changed_Time != null) {
			setChanged_Time(changed_Time);
		}
	}

	@JSON
	public long getBorrower_Id() {
		return _borrower_Id;
	}

	public void setBorrower_Id(long borrower_Id) {
		_borrower_Id = borrower_Id;
	}

	@JSON
	public long getAbacus_Person_Id() {
		return _abacus_Person_Id;
	}

	public void setAbacus_Person_Id(long abacus_Person_Id) {
		_abacus_Person_Id = abacus_Person_Id;
	}

	@JSON
	public String getVillage() {
		if (_village == null) {
			return StringPool.BLANK;
		}
		else {
			return _village;
		}
	}

	public void setVillage(String village) {
		_village = village;
	}

	@JSON
	public String getDistrict() {
		if (_district == null) {
			return StringPool.BLANK;
		}
		else {
			return _district;
		}
	}

	public void setDistrict(String district) {
		_district = district;
	}

	@JSON
	public String getPdf_Link() {
		if (_pdf_Link == null) {
			return StringPool.BLANK;
		}
		else {
			return _pdf_Link;
		}
	}

	public void setPdf_Link(String pdf_Link) {
		_pdf_Link = pdf_Link;
	}

	@JSON
	public double getCurrency() {
		return _currency;
	}

	public void setCurrency(double currency) {
		_currency = currency;
	}

	@JSON
	public String getChanged_By() {
		if (_changed_By == null) {
			return StringPool.BLANK;
		}
		else {
			return _changed_By;
		}
	}

	public void setChanged_By(String changed_By) {
		_changed_By = changed_By;
	}

	@JSON
	public long getChanged_Time() {
		return _changed_Time;
	}

	public void setChanged_Time(long changed_Time) {
		_changed_Time = changed_Time;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Borrower.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Borrower toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Borrower)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		BorrowerImpl borrowerImpl = new BorrowerImpl();

		borrowerImpl.setBorrower_Id(getBorrower_Id());
		borrowerImpl.setAbacus_Person_Id(getAbacus_Person_Id());
		borrowerImpl.setVillage(getVillage());
		borrowerImpl.setDistrict(getDistrict());
		borrowerImpl.setPdf_Link(getPdf_Link());
		borrowerImpl.setCurrency(getCurrency());
		borrowerImpl.setChanged_By(getChanged_By());
		borrowerImpl.setChanged_Time(getChanged_Time());

		borrowerImpl.resetOriginalValues();

		return borrowerImpl;
	}

	public int compareTo(Borrower borrower) {
		int value = 0;

		if (getBorrower_Id() < borrower.getBorrower_Id()) {
			value = -1;
		}
		else if (getBorrower_Id() > borrower.getBorrower_Id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Borrower borrower = null;

		try {
			borrower = (Borrower)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = borrower.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Borrower> toCacheModel() {
		BorrowerCacheModel borrowerCacheModel = new BorrowerCacheModel();

		borrowerCacheModel.borrower_Id = getBorrower_Id();

		borrowerCacheModel.abacus_Person_Id = getAbacus_Person_Id();

		borrowerCacheModel.village = getVillage();

		String village = borrowerCacheModel.village;

		if ((village != null) && (village.length() == 0)) {
			borrowerCacheModel.village = null;
		}

		borrowerCacheModel.district = getDistrict();

		String district = borrowerCacheModel.district;

		if ((district != null) && (district.length() == 0)) {
			borrowerCacheModel.district = null;
		}

		borrowerCacheModel.pdf_Link = getPdf_Link();

		String pdf_Link = borrowerCacheModel.pdf_Link;

		if ((pdf_Link != null) && (pdf_Link.length() == 0)) {
			borrowerCacheModel.pdf_Link = null;
		}

		borrowerCacheModel.currency = getCurrency();

		borrowerCacheModel.changed_By = getChanged_By();

		String changed_By = borrowerCacheModel.changed_By;

		if ((changed_By != null) && (changed_By.length() == 0)) {
			borrowerCacheModel.changed_By = null;
		}

		borrowerCacheModel.changed_Time = getChanged_Time();

		return borrowerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{borrower_Id=");
		sb.append(getBorrower_Id());
		sb.append(", abacus_Person_Id=");
		sb.append(getAbacus_Person_Id());
		sb.append(", village=");
		sb.append(getVillage());
		sb.append(", district=");
		sb.append(getDistrict());
		sb.append(", pdf_Link=");
		sb.append(getPdf_Link());
		sb.append(", currency=");
		sb.append(getCurrency());
		sb.append(", changed_By=");
		sb.append(getChanged_By());
		sb.append(", changed_Time=");
		sb.append(getChanged_Time());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.goodreturn.model.Borrower");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>borrower_Id</column-name><column-value><![CDATA[");
		sb.append(getBorrower_Id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>abacus_Person_Id</column-name><column-value><![CDATA[");
		sb.append(getAbacus_Person_Id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>village</column-name><column-value><![CDATA[");
		sb.append(getVillage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>district</column-name><column-value><![CDATA[");
		sb.append(getDistrict());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pdf_Link</column-name><column-value><![CDATA[");
		sb.append(getPdf_Link());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currency</column-name><column-value><![CDATA[");
		sb.append(getCurrency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>changed_By</column-name><column-value><![CDATA[");
		sb.append(getChanged_By());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>changed_Time</column-name><column-value><![CDATA[");
		sb.append(getChanged_Time());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Borrower.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Borrower.class
		};
	private long _borrower_Id;
	private long _abacus_Person_Id;
	private String _village;
	private String _district;
	private String _pdf_Link;
	private double _currency;
	private String _changed_By;
	private long _changed_Time;
	private Borrower _escapedModelProxy;
}