/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.goodreturn.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.goodreturn.model.BorrowerLoan;
import org.goodreturn.model.BorrowerLoanModel;
import org.goodreturn.model.BorrowerLoanSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BorrowerLoan service. Represents a row in the &quot;GoodReturn_BorrowerLoan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.goodreturn.model.BorrowerLoanModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BorrowerLoanImpl}.
 * </p>
 *
 * @author gilaa004
 * @see BorrowerLoanImpl
 * @see org.goodreturn.model.BorrowerLoan
 * @see org.goodreturn.model.BorrowerLoanModel
 * @generated
 */
@JSON(strict = true)
public class BorrowerLoanModelImpl extends BaseModelImpl<BorrowerLoan>
	implements BorrowerLoanModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a borrower loan model instance should use the {@link org.goodreturn.model.BorrowerLoan} interface instead.
	 */
	public static final String TABLE_NAME = "GoodReturn_BorrowerLoan";
	public static final Object[][] TABLE_COLUMNS = {
			{ "borrower_Loan_Id", Types.BIGINT },
			{ "borrower_Id", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table GoodReturn_BorrowerLoan (borrower_Loan_Id LONG not null primary key,borrower_Id LONG)";
	public static final String TABLE_SQL_DROP = "drop table GoodReturn_BorrowerLoan";
	public static final String ORDER_BY_JPQL = " ORDER BY borrowerLoan.borrower_Loan_Id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GoodReturn_BorrowerLoan.borrower_Loan_Id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.goodreturn.model.BorrowerLoan"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.goodreturn.model.BorrowerLoan"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.goodreturn.model.BorrowerLoan"),
			true);
	public static long BORROWER_ID_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BorrowerLoan toModel(BorrowerLoanSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BorrowerLoan model = new BorrowerLoanImpl();

		model.setBorrower_Loan_Id(soapModel.getBorrower_Loan_Id());
		model.setBorrower_Id(soapModel.getBorrower_Id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BorrowerLoan> toModels(BorrowerLoanSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BorrowerLoan> models = new ArrayList<BorrowerLoan>(soapModels.length);

		for (BorrowerLoanSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.goodreturn.model.BorrowerLoan"));

	public BorrowerLoanModelImpl() {
	}

	public long getPrimaryKey() {
		return _borrower_Loan_Id;
	}

	public void setPrimaryKey(long primaryKey) {
		setBorrower_Loan_Id(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_borrower_Loan_Id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return BorrowerLoan.class;
	}

	public String getModelClassName() {
		return BorrowerLoan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("borrower_Loan_Id", getBorrower_Loan_Id());
		attributes.put("borrower_Id", getBorrower_Id());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long borrower_Loan_Id = (Long)attributes.get("borrower_Loan_Id");

		if (borrower_Loan_Id != null) {
			setBorrower_Loan_Id(borrower_Loan_Id);
		}

		Long borrower_Id = (Long)attributes.get("borrower_Id");

		if (borrower_Id != null) {
			setBorrower_Id(borrower_Id);
		}
	}

	@JSON
	public long getBorrower_Loan_Id() {
		return _borrower_Loan_Id;
	}

	public void setBorrower_Loan_Id(long borrower_Loan_Id) {
		_columnBitmask = -1L;

		_borrower_Loan_Id = borrower_Loan_Id;
	}

	@JSON
	public long getBorrower_Id() {
		return _borrower_Id;
	}

	public void setBorrower_Id(long borrower_Id) {
		_columnBitmask |= BORROWER_ID_COLUMN_BITMASK;

		if (!_setOriginalBorrower_Id) {
			_setOriginalBorrower_Id = true;

			_originalBorrower_Id = _borrower_Id;
		}

		_borrower_Id = borrower_Id;
	}

	public long getOriginalBorrower_Id() {
		return _originalBorrower_Id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BorrowerLoan.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BorrowerLoan toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (BorrowerLoan)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		BorrowerLoanImpl borrowerLoanImpl = new BorrowerLoanImpl();

		borrowerLoanImpl.setBorrower_Loan_Id(getBorrower_Loan_Id());
		borrowerLoanImpl.setBorrower_Id(getBorrower_Id());

		borrowerLoanImpl.resetOriginalValues();

		return borrowerLoanImpl;
	}

	public int compareTo(BorrowerLoan borrowerLoan) {
		int value = 0;

		if (getBorrower_Loan_Id() < borrowerLoan.getBorrower_Loan_Id()) {
			value = -1;
		}
		else if (getBorrower_Loan_Id() > borrowerLoan.getBorrower_Loan_Id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		BorrowerLoan borrowerLoan = null;

		try {
			borrowerLoan = (BorrowerLoan)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = borrowerLoan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BorrowerLoanModelImpl borrowerLoanModelImpl = this;

		borrowerLoanModelImpl._originalBorrower_Id = borrowerLoanModelImpl._borrower_Id;

		borrowerLoanModelImpl._setOriginalBorrower_Id = false;

		borrowerLoanModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BorrowerLoan> toCacheModel() {
		BorrowerLoanCacheModel borrowerLoanCacheModel = new BorrowerLoanCacheModel();

		borrowerLoanCacheModel.borrower_Loan_Id = getBorrower_Loan_Id();

		borrowerLoanCacheModel.borrower_Id = getBorrower_Id();

		return borrowerLoanCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{borrower_Loan_Id=");
		sb.append(getBorrower_Loan_Id());
		sb.append(", borrower_Id=");
		sb.append(getBorrower_Id());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("org.goodreturn.model.BorrowerLoan");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>borrower_Loan_Id</column-name><column-value><![CDATA[");
		sb.append(getBorrower_Loan_Id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>borrower_Id</column-name><column-value><![CDATA[");
		sb.append(getBorrower_Id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BorrowerLoan.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			BorrowerLoan.class
		};
	private long _borrower_Loan_Id;
	private long _borrower_Id;
	private long _originalBorrower_Id;
	private boolean _setOriginalBorrower_Id;
	private long _columnBitmask;
	private BorrowerLoan _escapedModelProxy;
}