/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TeamLender service. Represents a row in the &quot;KYLE_TeamLender&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.TeamLenderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.TeamLenderImpl}.
 * </p>
 *
 * @author gilaa004
 * @see TeamLender
 * @see com.test.model.impl.TeamLenderImpl
 * @see com.test.model.impl.TeamLenderModelImpl
 * @generated
 */
public interface TeamLenderModel extends BaseModel<TeamLender> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team lender model instance should use the {@link TeamLender} interface instead.
	 */

	/**
	 * Returns the primary key of this team lender.
	 *
	 * @return the primary key of this team lender
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this team lender.
	 *
	 * @param primaryKey the primary key of this team lender
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the teamlender_ ID of this team lender.
	 *
	 * @return the teamlender_ ID of this team lender
	 */
	public long getTeamlender_Id();

	/**
	 * Sets the teamlender_ ID of this team lender.
	 *
	 * @param teamlender_Id the teamlender_ ID of this team lender
	 */
	public void setTeamlender_Id(long teamlender_Id);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TeamLender teamLender);

	public int hashCode();

	public CacheModel<TeamLender> toCacheModel();

	public TeamLender toEscapedModel();

	public String toString();

	public String toXmlString();
}