/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.GoodReturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Loan service. Represents a row in the &quot;WEAL_Loan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.GoodReturn.model.impl.LoanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.GoodReturn.model.impl.LoanImpl}.
 * </p>
 *
 * @author gilaa004
 * @see Loan
 * @see org.GoodReturn.model.impl.LoanImpl
 * @see org.GoodReturn.model.impl.LoanModelImpl
 * @generated
 */
public interface LoanModel extends BaseModel<Loan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a loan model instance should use the {@link Loan} interface instead.
	 */

	/**
	 * Returns the primary key of this loan.
	 *
	 * @return the primary key of this loan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this loan.
	 *
	 * @param primaryKey the primary key of this loan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the loan_ ID of this loan.
	 *
	 * @return the loan_ ID of this loan
	 */
	public long getLoan_Id();

	/**
	 * Sets the loan_ ID of this loan.
	 *
	 * @param loan_Id the loan_ ID of this loan
	 */
	public void setLoan_Id(long loan_Id);

	/**
	 * Returns the is_ partially_ funded of this loan.
	 *
	 * @return the is_ partially_ funded of this loan
	 */
	public boolean getIs_Partially_Funded();

	/**
	 * Returns <code>true</code> if this loan is is_ partially_ funded.
	 *
	 * @return <code>true</code> if this loan is is_ partially_ funded; <code>false</code> otherwise
	 */
	public boolean isIs_Partially_Funded();

	/**
	 * Sets whether this loan is is_ partially_ funded.
	 *
	 * @param is_Partially_Funded the is_ partially_ funded of this loan
	 */
	public void setIs_Partially_Funded(boolean is_Partially_Funded);

	/**
	 * Returns the amount_ requested of this loan.
	 *
	 * @return the amount_ requested of this loan
	 */
	public double getAmount_Requested();

	/**
	 * Sets the amount_ requested of this loan.
	 *
	 * @param amount_Requested the amount_ requested of this loan
	 */
	public void setAmount_Requested(double amount_Requested);

	/**
	 * Returns the amount_ fulfilled of this loan.
	 *
	 * @return the amount_ fulfilled of this loan
	 */
	public double getAmount_Fulfilled();

	/**
	 * Sets the amount_ fulfilled of this loan.
	 *
	 * @param amount_Fulfilled the amount_ fulfilled of this loan
	 */
	public void setAmount_Fulfilled(double amount_Fulfilled);

	/**
	 * Returns the expiry_ date of this loan.
	 *
	 * @return the expiry_ date of this loan
	 */
	public Date getExpiry_Date();

	/**
	 * Sets the expiry_ date of this loan.
	 *
	 * @param expiry_Date the expiry_ date of this loan
	 */
	public void setExpiry_Date(Date expiry_Date);

	/**
	 * Returns the date_ requisitioned of this loan.
	 *
	 * @return the date_ requisitioned of this loan
	 */
	public Date getDate_Requisitioned();

	/**
	 * Sets the date_ requisitioned of this loan.
	 *
	 * @param date_Requisitioned the date_ requisitioned of this loan
	 */
	public void setDate_Requisitioned(Date date_Requisitioned);

	/**
	 * Returns the date_ of_ fulfillment of this loan.
	 *
	 * @return the date_ of_ fulfillment of this loan
	 */
	public Date getDate_Of_Fulfillment();

	/**
	 * Sets the date_ of_ fulfillment of this loan.
	 *
	 * @param date_Of_Fulfillment the date_ of_ fulfillment of this loan
	 */
	public void setDate_Of_Fulfillment(Date date_Of_Fulfillment);

	/**
	 * Returns the start_ date of this loan.
	 *
	 * @return the start_ date of this loan
	 */
	public Date getStart_Date();

	/**
	 * Sets the start_ date of this loan.
	 *
	 * @param start_Date the start_ date of this loan
	 */
	public void setStart_Date(Date start_Date);

	/**
	 * Returns the end_ date of this loan.
	 *
	 * @return the end_ date of this loan
	 */
	public Date getEnd_Date();

	/**
	 * Sets the end_ date of this loan.
	 *
	 * @param end_Date the end_ date of this loan
	 */
	public void setEnd_Date(Date end_Date);

	/**
	 * Returns the company_ ID of this loan.
	 *
	 * @return the company_ ID of this loan
	 */
	public long getCompany_Id();

	/**
	 * Sets the company_ ID of this loan.
	 *
	 * @param company_Id the company_ ID of this loan
	 */
	public void setCompany_Id(long company_Id);

	/**
	 * Returns the group_ ID of this loan.
	 *
	 * @return the group_ ID of this loan
	 */
	public long getGroup_Id();

	/**
	 * Sets the group_ ID of this loan.
	 *
	 * @param group_Id the group_ ID of this loan
	 */
	public void setGroup_Id(long group_Id);

	/**
	 * Returns the amount_ monthly of this loan.
	 *
	 * @return the amount_ monthly of this loan
	 */
	public int getAmount_Monthly();

	/**
	 * Sets the amount_ monthly of this loan.
	 *
	 * @param amount_Monthly the amount_ monthly of this loan
	 */
	public void setAmount_Monthly(int amount_Monthly);

	/**
	 * Returns the account_ information of this loan.
	 *
	 * @return the account_ information of this loan
	 */
	@AutoEscape
	public String getAccount_Information();

	/**
	 * Sets the account_ information of this loan.
	 *
	 * @param account_Information the account_ information of this loan
	 */
	public void setAccount_Information(String account_Information);

	/**
	 * Returns the day_ of_ withdrawal of this loan.
	 *
	 * @return the day_ of_ withdrawal of this loan
	 */
	public int getDay_Of_Withdrawal();

	/**
	 * Sets the day_ of_ withdrawal of this loan.
	 *
	 * @param day_Of_Withdrawal the day_ of_ withdrawal of this loan
	 */
	public void setDay_Of_Withdrawal(int day_Of_Withdrawal);

	/**
	 * Returns the final_ payment_ date of this loan.
	 *
	 * @return the final_ payment_ date of this loan
	 */
	public Date getFinal_Payment_Date();

	/**
	 * Sets the final_ payment_ date of this loan.
	 *
	 * @param final_Payment_Date the final_ payment_ date of this loan
	 */
	public void setFinal_Payment_Date(Date final_Payment_Date);

	/**
	 * Returns the loan_ reason of this loan.
	 *
	 * @return the loan_ reason of this loan
	 */
	@AutoEscape
	public String getLoan_Reason();

	/**
	 * Sets the loan_ reason of this loan.
	 *
	 * @param loan_Reason the loan_ reason of this loan
	 */
	public void setLoan_Reason(String loan_Reason);

	/**
	 * Returns the loan_ type of this loan.
	 *
	 * @return the loan_ type of this loan
	 */
	@AutoEscape
	public String getLoan_Type();

	/**
	 * Sets the loan_ type of this loan.
	 *
	 * @param loan_Type the loan_ type of this loan
	 */
	public void setLoan_Type(String loan_Type);

	/**
	 * Returns the loan_ time of this loan.
	 *
	 * @return the loan_ time of this loan
	 */
	@AutoEscape
	public String getLoan_Time();

	/**
	 * Sets the loan_ time of this loan.
	 *
	 * @param loan_Time the loan_ time of this loan
	 */
	public void setLoan_Time(String loan_Time);

	/**
	 * Returns the funding_ preferences of this loan.
	 *
	 * @return the funding_ preferences of this loan
	 */
	@AutoEscape
	public String getFunding_Preferences();

	/**
	 * Sets the funding_ preferences of this loan.
	 *
	 * @param funding_Preferences the funding_ preferences of this loan
	 */
	public void setFunding_Preferences(String funding_Preferences);

	/**
	 * Returns the maturity of this loan.
	 *
	 * @return the maturity of this loan
	 */
	@AutoEscape
	public String getMaturity();

	/**
	 * Sets the maturity of this loan.
	 *
	 * @param maturity the maturity of this loan
	 */
	public void setMaturity(String maturity);

	/**
	 * Returns the repayments of this loan.
	 *
	 * @return the repayments of this loan
	 */
	public double getRepayments();

	/**
	 * Sets the repayments of this loan.
	 *
	 * @param repayments the repayments of this loan
	 */
	public void setRepayments(double repayments);

	/**
	 * Returns the status of this loan.
	 *
	 * @return the status of this loan
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this loan.
	 *
	 * @param status the status of this loan
	 */
	public void setStatus(String status);

	/**
	 * Returns the payment_ type of this loan.
	 *
	 * @return the payment_ type of this loan
	 */
	@AutoEscape
	public String getPayment_Type();

	/**
	 * Sets the payment_ type of this loan.
	 *
	 * @param payment_Type the payment_ type of this loan
	 */
	public void setPayment_Type(String payment_Type);

	/**
	 * Returns the payment_ receipt of this loan.
	 *
	 * @return the payment_ receipt of this loan
	 */
	@AutoEscape
	public String getPayment_Receipt();

	/**
	 * Sets the payment_ receipt of this loan.
	 *
	 * @param payment_Receipt the payment_ receipt of this loan
	 */
	public void setPayment_Receipt(String payment_Receipt);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Loan loan);

	public int hashCode();

	public CacheModel<Loan> toCacheModel();

	public Loan toEscapedModel();

	public String toString();

	public String toXmlString();
}