/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.GoodReturn.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Supplementary_Table service. Represents a row in the &quot;WEAL_Supplementary_Table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.GoodReturn.model.impl.Supplementary_TableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.GoodReturn.model.impl.Supplementary_TableImpl}.
 * </p>
 *
 * @author gilaa004
 * @see Supplementary_Table
 * @see org.GoodReturn.model.impl.Supplementary_TableImpl
 * @see org.GoodReturn.model.impl.Supplementary_TableModelImpl
 * @generated
 */
public interface Supplementary_TableModel extends BaseModel<Supplementary_Table> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a supplementary_ table model instance should use the {@link Supplementary_Table} interface instead.
	 */

	/**
	 * Returns the primary key of this supplementary_ table.
	 *
	 * @return the primary key of this supplementary_ table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this supplementary_ table.
	 *
	 * @param primaryKey the primary key of this supplementary_ table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the table_ ID of this supplementary_ table.
	 *
	 * @return the table_ ID of this supplementary_ table
	 */
	public long getTable_Id();

	/**
	 * Sets the table_ ID of this supplementary_ table.
	 *
	 * @param table_Id the table_ ID of this supplementary_ table
	 */
	public void setTable_Id(long table_Id);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Supplementary_Table supplementary_Table);

	public int hashCode();

	public CacheModel<Supplementary_Table> toCacheModel();

	public Supplementary_Table toEscapedModel();

	public String toString();

	public String toXmlString();
}