/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.GoodReturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Team service. Represents a row in the &quot;WEAL_Team&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.GoodReturn.model.impl.TeamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.GoodReturn.model.impl.TeamImpl}.
 * </p>
 *
 * @author gilaa004
 * @see Team
 * @see org.GoodReturn.model.impl.TeamImpl
 * @see org.GoodReturn.model.impl.TeamModelImpl
 * @generated
 */
public interface TeamModel extends BaseModel<Team> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team model instance should use the {@link Team} interface instead.
	 */

	/**
	 * Returns the primary key of this team.
	 *
	 * @return the primary key of this team
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this team.
	 *
	 * @param primaryKey the primary key of this team
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the team_ ID of this team.
	 *
	 * @return the team_ ID of this team
	 */
	public long getTeam_Id();

	/**
	 * Sets the team_ ID of this team.
	 *
	 * @param team_Id the team_ ID of this team
	 */
	public void setTeam_Id(long team_Id);

	/**
	 * Returns the team_ name of this team.
	 *
	 * @return the team_ name of this team
	 */
	@AutoEscape
	public String getTeam_Name();

	/**
	 * Sets the team_ name of this team.
	 *
	 * @param team_Name the team_ name of this team
	 */
	public void setTeam_Name(String team_Name);

	/**
	 * Returns the amount_ lent of this team.
	 *
	 * @return the amount_ lent of this team
	 */
	@AutoEscape
	public String getAmount_Lent();

	/**
	 * Sets the amount_ lent of this team.
	 *
	 * @param amount_Lent the amount_ lent of this team
	 */
	public void setAmount_Lent(String amount_Lent);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Team team);

	public int hashCode();

	public CacheModel<Team> toCacheModel();

	public Team toEscapedModel();

	public String toString();

	public String toXmlString();
}