/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.goodreturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BorrowerLoan service. Represents a row in the &quot;GoodReturn_BorrowerLoan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.goodreturn.model.impl.BorrowerLoanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.goodreturn.model.impl.BorrowerLoanImpl}.
 * </p>
 *
 * @author gilaa004
 * @see BorrowerLoan
 * @see org.goodreturn.model.impl.BorrowerLoanImpl
 * @see org.goodreturn.model.impl.BorrowerLoanModelImpl
 * @generated
 */
public interface BorrowerLoanModel extends BaseModel<BorrowerLoan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a borrower loan model instance should use the {@link BorrowerLoan} interface instead.
	 */

	/**
	 * Returns the primary key of this borrower loan.
	 *
	 * @return the primary key of this borrower loan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this borrower loan.
	 *
	 * @param primaryKey the primary key of this borrower loan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the abacus_ borrower_ loan_ ID of this borrower loan.
	 *
	 * @return the abacus_ borrower_ loan_ ID of this borrower loan
	 */
	public long getAbacus_Borrower_Loan_Id();

	/**
	 * Sets the abacus_ borrower_ loan_ ID of this borrower loan.
	 *
	 * @param abacus_Borrower_Loan_Id the abacus_ borrower_ loan_ ID of this borrower loan
	 */
	public void setAbacus_Borrower_Loan_Id(long abacus_Borrower_Loan_Id);

	/**
	 * Returns the borrower_ ID of this borrower loan.
	 *
	 * @return the borrower_ ID of this borrower loan
	 */
	public long getBorrower_Id();

	/**
	 * Sets the borrower_ ID of this borrower loan.
	 *
	 * @param borrower_Id the borrower_ ID of this borrower loan
	 */
	public void setBorrower_Id(long borrower_Id);

	/**
	 * Returns the abacus_mfi_ ID of this borrower loan.
	 *
	 * @return the abacus_mfi_ ID of this borrower loan
	 */
	public long getAbacus_mfi_Id();

	/**
	 * Sets the abacus_mfi_ ID of this borrower loan.
	 *
	 * @param abacus_mfi_Id the abacus_mfi_ ID of this borrower loan
	 */
	public void setAbacus_mfi_Id(long abacus_mfi_Id);

	/**
	 * Returns the changed_ by of this borrower loan.
	 *
	 * @return the changed_ by of this borrower loan
	 */
	@AutoEscape
	public String getChanged_By();

	/**
	 * Sets the changed_ by of this borrower loan.
	 *
	 * @param changed_By the changed_ by of this borrower loan
	 */
	public void setChanged_By(String changed_By);

	/**
	 * Returns the changed_ time of this borrower loan.
	 *
	 * @return the changed_ time of this borrower loan
	 */
	@AutoEscape
	public String getChanged_Time();

	/**
	 * Sets the changed_ time of this borrower loan.
	 *
	 * @param changed_Time the changed_ time of this borrower loan
	 */
	public void setChanged_Time(String changed_Time);

	/**
	 * Returns the group ID of this borrower loan.
	 *
	 * @return the group ID of this borrower loan
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this borrower loan.
	 *
	 * @param groupId the group ID of this borrower loan
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this borrower loan.
	 *
	 * @return the company ID of this borrower loan
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this borrower loan.
	 *
	 * @param companyId the company ID of this borrower loan
	 */
	public void setCompanyId(long companyId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(BorrowerLoan borrowerLoan);

	public int hashCode();

	public CacheModel<BorrowerLoan> toCacheModel();

	public BorrowerLoan toEscapedModel();

	public String toString();

	public String toXmlString();
}