/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.GoodReturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Borrower service. Represents a row in the &quot;GoodReturn_Borrower&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.GoodReturn.model.impl.BorrowerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.GoodReturn.model.impl.BorrowerImpl}.
 * </p>
 *
 * @author gilaa004
 * @see Borrower
 * @see org.GoodReturn.model.impl.BorrowerImpl
 * @see org.GoodReturn.model.impl.BorrowerModelImpl
 * @generated
 */
public interface BorrowerModel extends BaseModel<Borrower> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a borrower model instance should use the {@link Borrower} interface instead.
	 */

	/**
	 * Returns the primary key of this borrower.
	 *
	 * @return the primary key of this borrower
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this borrower.
	 *
	 * @param primaryKey the primary key of this borrower
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the abacus_ borrower_ ID of this borrower.
	 *
	 * @return the abacus_ borrower_ ID of this borrower
	 */
	public long getAbacus_Borrower_Id();

	/**
	 * Sets the abacus_ borrower_ ID of this borrower.
	 *
	 * @param abacus_Borrower_Id the abacus_ borrower_ ID of this borrower
	 */
	public void setAbacus_Borrower_Id(long abacus_Borrower_Id);

	/**
	 * Returns the write_ off_ date of this borrower.
	 *
	 * @return the write_ off_ date of this borrower
	 */
	public Date getWrite_Off_Date();

	/**
	 * Sets the write_ off_ date of this borrower.
	 *
	 * @param write_Off_Date the write_ off_ date of this borrower
	 */
	public void setWrite_Off_Date(Date write_Off_Date);

	/**
	 * Returns the phone of this borrower.
	 *
	 * @return the phone of this borrower
	 */
	public long getPhone();

	/**
	 * Sets the phone of this borrower.
	 *
	 * @param phone the phone of this borrower
	 */
	public void setPhone(long phone);

	/**
	 * Returns the wait_ time of this borrower.
	 *
	 * @return the wait_ time of this borrower
	 */
	public long getWait_Time();

	/**
	 * Sets the wait_ time of this borrower.
	 *
	 * @param wait_Time the wait_ time of this borrower
	 */
	public void setWait_Time(long wait_Time);

	/**
	 * Returns the country of this borrower.
	 *
	 * @return the country of this borrower
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this borrower.
	 *
	 * @param country the country of this borrower
	 */
	public void setCountry(String country);

	/**
	 * Returns the amount_ needed of this borrower.
	 *
	 * @return the amount_ needed of this borrower
	 */
	public double getAmount_Needed();

	/**
	 * Sets the amount_ needed of this borrower.
	 *
	 * @param amount_Needed the amount_ needed of this borrower
	 */
	public void setAmount_Needed(double amount_Needed);

	/**
	 * Returns the amount_ needed_ a u d of this borrower.
	 *
	 * @return the amount_ needed_ a u d of this borrower
	 */
	public double getAmount_Needed_AUD();

	/**
	 * Sets the amount_ needed_ a u d of this borrower.
	 *
	 * @param amount_Needed_AUD the amount_ needed_ a u d of this borrower
	 */
	public void setAmount_Needed_AUD(double amount_Needed_AUD);

	/**
	 * Returns the type_ of_ person of this borrower.
	 *
	 * @return the type_ of_ person of this borrower
	 */
	@AutoEscape
	public String getType_Of_Person();

	/**
	 * Sets the type_ of_ person of this borrower.
	 *
	 * @param type_Of_Person the type_ of_ person of this borrower
	 */
	public void setType_Of_Person(String type_Of_Person);

	/**
	 * Returns the village of this borrower.
	 *
	 * @return the village of this borrower
	 */
	@AutoEscape
	public String getVillage();

	/**
	 * Sets the village of this borrower.
	 *
	 * @param village the village of this borrower
	 */
	public void setVillage(String village);

	/**
	 * Returns the district of this borrower.
	 *
	 * @return the district of this borrower
	 */
	@AutoEscape
	public String getDistrict();

	/**
	 * Sets the district of this borrower.
	 *
	 * @param district the district of this borrower
	 */
	public void setDistrict(String district);

	/**
	 * Returns the pdf_ link of this borrower.
	 *
	 * @return the pdf_ link of this borrower
	 */
	@AutoEscape
	public String getPdf_Link();

	/**
	 * Sets the pdf_ link of this borrower.
	 *
	 * @param pdf_Link the pdf_ link of this borrower
	 */
	public void setPdf_Link(String pdf_Link);

	/**
	 * Returns the currency of this borrower.
	 *
	 * @return the currency of this borrower
	 */
	public double getCurrency();

	/**
	 * Sets the currency of this borrower.
	 *
	 * @param currency the currency of this borrower
	 */
	public void setCurrency(double currency);

	/**
	 * Returns the date_ applied of this borrower.
	 *
	 * @return the date_ applied of this borrower
	 */
	public Date getDate_Applied();

	/**
	 * Sets the date_ applied of this borrower.
	 *
	 * @param date_Applied the date_ applied of this borrower
	 */
	public void setDate_Applied(Date date_Applied);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Borrower borrower);

	public int hashCode();

	public CacheModel<Borrower> toCacheModel();

	public Borrower toEscapedModel();

	public String toString();

	public String toXmlString();
}