/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.GoodReturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Person service. Represents a row in the &quot;GoodReturn_Person&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.GoodReturn.model.impl.PersonModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.GoodReturn.model.impl.PersonImpl}.
 * </p>
 *
 * @author gilaa004
 * @see Person
 * @see org.GoodReturn.model.impl.PersonImpl
 * @see org.GoodReturn.model.impl.PersonModelImpl
 * @generated
 */
public interface PersonModel extends BaseModel<Person> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a person model instance should use the {@link Person} interface instead.
	 */

	/**
	 * Returns the primary key of this person.
	 *
	 * @return the primary key of this person
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this person.
	 *
	 * @param primaryKey the primary key of this person
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the abacus_ person_ ID of this person.
	 *
	 * @return the abacus_ person_ ID of this person
	 */
	public long getAbacus_Person_Id();

	/**
	 * Sets the abacus_ person_ ID of this person.
	 *
	 * @param abacus_Person_Id the abacus_ person_ ID of this person
	 */
	public void setAbacus_Person_Id(long abacus_Person_Id);

	/**
	 * Returns the first_ name of this person.
	 *
	 * @return the first_ name of this person
	 */
	@AutoEscape
	public String getFirst_Name();

	/**
	 * Sets the first_ name of this person.
	 *
	 * @param first_Name the first_ name of this person
	 */
	public void setFirst_Name(String first_Name);

	/**
	 * Returns the last_ name of this person.
	 *
	 * @return the last_ name of this person
	 */
	@AutoEscape
	public String getLast_Name();

	/**
	 * Sets the last_ name of this person.
	 *
	 * @param last_Name the last_ name of this person
	 */
	public void setLast_Name(String last_Name);

	/**
	 * Returns the email of this person.
	 *
	 * @return the email of this person
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this person.
	 *
	 * @param email the email of this person
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this person.
	 *
	 * @return the address of this person
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this person.
	 *
	 * @param address the address of this person
	 */
	public void setAddress(String address);

	/**
	 * Returns the address_ type of this person.
	 *
	 * @return the address_ type of this person
	 */
	@AutoEscape
	public String getAddress_Type();

	/**
	 * Sets the address_ type of this person.
	 *
	 * @param address_Type the address_ type of this person
	 */
	public void setAddress_Type(String address_Type);

	/**
	 * Returns the country of this person.
	 *
	 * @return the country of this person
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this person.
	 *
	 * @param country the country of this person
	 */
	public void setCountry(String country);

	/**
	 * Returns the gender of this person.
	 *
	 * @return the gender of this person
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this person.
	 *
	 * @param gender the gender of this person
	 */
	public void setGender(String gender);

	/**
	 * Returns the status of this person.
	 *
	 * @return the status of this person
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this person.
	 *
	 * @param status the status of this person
	 */
	public void setStatus(String status);

	/**
	 * Returns the photo_ u r l of this person.
	 *
	 * @return the photo_ u r l of this person
	 */
	@AutoEscape
	public String getPhoto_URL();

	/**
	 * Sets the photo_ u r l of this person.
	 *
	 * @param photo_URL the photo_ u r l of this person
	 */
	public void setPhoto_URL(String photo_URL);

	/**
	 * Returns the occupation of this person.
	 *
	 * @return the occupation of this person
	 */
	@AutoEscape
	public String getOccupation();

	/**
	 * Sets the occupation of this person.
	 *
	 * @param occupation the occupation of this person
	 */
	public void setOccupation(String occupation);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Person person);

	public int hashCode();

	public CacheModel<Person> toCacheModel();

	public Person toEscapedModel();

	public String toString();

	public String toXmlString();
}