/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.goodreturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Story service. Represents a row in the &quot;GoodReturn_Story&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.goodreturn.model.impl.StoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.goodreturn.model.impl.StoryImpl}.
 * </p>
 *
 * @author gilaa004
 * @see Story
 * @see org.goodreturn.model.impl.StoryImpl
 * @see org.goodreturn.model.impl.StoryModelImpl
 * @generated
 */
public interface StoryModel extends BaseModel<Story> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a story model instance should use the {@link Story} interface instead.
	 */

	/**
	 * Returns the primary key of this story.
	 *
	 * @return the primary key of this story
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this story.
	 *
	 * @param primaryKey the primary key of this story
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this story.
	 *
	 * @return the uuid of this story
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this story.
	 *
	 * @param uuid the uuid of this story
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the story_ ID of this story.
	 *
	 * @return the story_ ID of this story
	 */
	public long getStory_Id();

	/**
	 * Sets the story_ ID of this story.
	 *
	 * @param story_Id the story_ ID of this story
	 */
	public void setStory_Id(long story_Id);

	/**
	 * Returns the abacus_ borrower_ loan_ ID of this story.
	 *
	 * @return the abacus_ borrower_ loan_ ID of this story
	 */
	public long getAbacus_Borrower_Loan_Id();

	/**
	 * Sets the abacus_ borrower_ loan_ ID of this story.
	 *
	 * @param abacus_Borrower_Loan_Id the abacus_ borrower_ loan_ ID of this story
	 */
	public void setAbacus_Borrower_Loan_Id(long abacus_Borrower_Loan_Id);

	/**
	 * Returns the story_ type of this story.
	 *
	 * @return the story_ type of this story
	 */
	@AutoEscape
	public String getStory_Type();

	/**
	 * Sets the story_ type of this story.
	 *
	 * @param story_Type the story_ type of this story
	 */
	public void setStory_Type(String story_Type);

	/**
	 * Returns the story_ text of this story.
	 *
	 * @return the story_ text of this story
	 */
	@AutoEscape
	public String getStory_Text();

	/**
	 * Sets the story_ text of this story.
	 *
	 * @param story_Text the story_ text of this story
	 */
	public void setStory_Text(String story_Text);

	/**
	 * Returns the video_ url of this story.
	 *
	 * @return the video_ url of this story
	 */
	@AutoEscape
	public String getVideo_Url();

	/**
	 * Sets the video_ url of this story.
	 *
	 * @param video_Url the video_ url of this story
	 */
	public void setVideo_Url(String video_Url);

	/**
	 * Returns the is_ good_ enough_ for_ marketing of this story.
	 *
	 * @return the is_ good_ enough_ for_ marketing of this story
	 */
	public boolean getIs_Good_Enough_For_Marketing();

	/**
	 * Returns <code>true</code> if this story is is_ good_ enough_ for_ marketing.
	 *
	 * @return <code>true</code> if this story is is_ good_ enough_ for_ marketing; <code>false</code> otherwise
	 */
	public boolean isIs_Good_Enough_For_Marketing();

	/**
	 * Sets whether this story is is_ good_ enough_ for_ marketing.
	 *
	 * @param is_Good_Enough_For_Marketing the is_ good_ enough_ for_ marketing of this story
	 */
	public void setIs_Good_Enough_For_Marketing(
		boolean is_Good_Enough_For_Marketing);

	/**
	 * Returns the is_ good_ enough_ for_ story of this story.
	 *
	 * @return the is_ good_ enough_ for_ story of this story
	 */
	public boolean getIs_Good_Enough_For_Story();

	/**
	 * Returns <code>true</code> if this story is is_ good_ enough_ for_ story.
	 *
	 * @return <code>true</code> if this story is is_ good_ enough_ for_ story; <code>false</code> otherwise
	 */
	public boolean isIs_Good_Enough_For_Story();

	/**
	 * Sets whether this story is is_ good_ enough_ for_ story.
	 *
	 * @param is_Good_Enough_For_Story the is_ good_ enough_ for_ story of this story
	 */
	public void setIs_Good_Enough_For_Story(boolean is_Good_Enough_For_Story);

	/**
	 * Returns the status of this story.
	 *
	 * @return the status of this story
	 */
	public int getStatus();

	/**
	 * Sets the status of this story.
	 *
	 * @param status the status of this story
	 */
	public void setStatus(int status);

	/**
	 * Returns the status_ by_ user_ ID of this story.
	 *
	 * @return the status_ by_ user_ ID of this story
	 */
	public long getStatus_By_User_Id();

	/**
	 * Sets the status_ by_ user_ ID of this story.
	 *
	 * @param status_By_User_Id the status_ by_ user_ ID of this story
	 */
	public void setStatus_By_User_Id(long status_By_User_Id);

	/**
	 * Returns the status_ by_ user_ name of this story.
	 *
	 * @return the status_ by_ user_ name of this story
	 */
	@AutoEscape
	public String getStatus_By_User_Name();

	/**
	 * Sets the status_ by_ user_ name of this story.
	 *
	 * @param status_By_User_Name the status_ by_ user_ name of this story
	 */
	public void setStatus_By_User_Name(String status_By_User_Name);

	/**
	 * Returns the status_ date of this story.
	 *
	 * @return the status_ date of this story
	 */
	public Date getStatus_Date();

	/**
	 * Sets the status_ date of this story.
	 *
	 * @param status_Date the status_ date of this story
	 */
	public void setStatus_Date(Date status_Date);

	/**
	 * Returns the company ID of this story.
	 *
	 * @return the company ID of this story
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this story.
	 *
	 * @param companyId the company ID of this story
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this story.
	 *
	 * @return the group ID of this story
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this story.
	 *
	 * @param groupId the group ID of this story
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this story.
	 *
	 * @return the user ID of this story
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this story.
	 *
	 * @param userId the user ID of this story
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this story.
	 *
	 * @return the user uuid of this story
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this story.
	 *
	 * @param userUuid the user uuid of this story
	 */
	public void setUserUuid(String userUuid);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Story story);

	public int hashCode();

	public CacheModel<Story> toCacheModel();

	public Story toEscapedModel();

	public String toString();

	public String toXmlString();
}