/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.goodreturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TeamLender service. Represents a row in the &quot;GoodReturn_TeamLender&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.goodreturn.model.impl.TeamLenderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.goodreturn.model.impl.TeamLenderImpl}.
 * </p>
 *
 * @author gilaa004
 * @see TeamLender
 * @see org.goodreturn.model.impl.TeamLenderImpl
 * @see org.goodreturn.model.impl.TeamLenderModelImpl
 * @generated
 */
public interface TeamLenderModel extends BaseModel<TeamLender> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team lender model instance should use the {@link TeamLender} interface instead.
	 */

	/**
	 * Returns the primary key of this team lender.
	 *
	 * @return the primary key of this team lender
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this team lender.
	 *
	 * @param primaryKey the primary key of this team lender
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the team_lender_ ID of this team lender.
	 *
	 * @return the team_lender_ ID of this team lender
	 */
	public long getTeam_lender_Id();

	/**
	 * Sets the team_lender_ ID of this team lender.
	 *
	 * @param team_lender_Id the team_lender_ ID of this team lender
	 */
	public void setTeam_lender_Id(long team_lender_Id);

	/**
	 * Returns the lender_ ID of this team lender.
	 *
	 * @return the lender_ ID of this team lender
	 */
	public long getLender_Id();

	/**
	 * Sets the lender_ ID of this team lender.
	 *
	 * @param lender_Id the lender_ ID of this team lender
	 */
	public void setLender_Id(long lender_Id);

	/**
	 * Returns the team_ ID of this team lender.
	 *
	 * @return the team_ ID of this team lender
	 */
	public long getTeam_Id();

	/**
	 * Sets the team_ ID of this team lender.
	 *
	 * @param team_Id the team_ ID of this team lender
	 */
	public void setTeam_Id(long team_Id);

	/**
	 * Returns the changed_ by of this team lender.
	 *
	 * @return the changed_ by of this team lender
	 */
	@AutoEscape
	public String getChanged_By();

	/**
	 * Sets the changed_ by of this team lender.
	 *
	 * @param changed_By the changed_ by of this team lender
	 */
	public void setChanged_By(String changed_By);

	/**
	 * Returns the changed_ time of this team lender.
	 *
	 * @return the changed_ time of this team lender
	 */
	public long getChanged_Time();

	/**
	 * Sets the changed_ time of this team lender.
	 *
	 * @param changed_Time the changed_ time of this team lender
	 */
	public void setChanged_Time(long changed_Time);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TeamLender teamLender);

	public int hashCode();

	public CacheModel<TeamLender> toCacheModel();

	public TeamLender toEscapedModel();

	public String toString();

	public String toXmlString();
}