/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.goodreturn.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TempBl service. Represents a row in the &quot;GoodReturn_TempBl&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.goodreturn.model.impl.TempBlModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.goodreturn.model.impl.TempBlImpl}.
 * </p>
 *
 * @author gilaa004
 * @see TempBl
 * @see org.goodreturn.model.impl.TempBlImpl
 * @see org.goodreturn.model.impl.TempBlModelImpl
 * @generated
 */
public interface TempBlModel extends BaseModel<TempBl> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp bl model instance should use the {@link TempBl} interface instead.
	 */

	/**
	 * Returns the primary key of this temp bl.
	 *
	 * @return the primary key of this temp bl
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp bl.
	 *
	 * @param primaryKey the primary key of this temp bl
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the borrower_ name of this temp bl.
	 *
	 * @return the borrower_ name of this temp bl
	 */
	@AutoEscape
	public String getBorrower_Name();

	/**
	 * Sets the borrower_ name of this temp bl.
	 *
	 * @param borrower_Name the borrower_ name of this temp bl
	 */
	public void setBorrower_Name(String borrower_Name);

	/**
	 * Returns the borrower_ loan_ ID of this temp bl.
	 *
	 * @return the borrower_ loan_ ID of this temp bl
	 */
	public long getBorrower_Loan_Id();

	/**
	 * Sets the borrower_ loan_ ID of this temp bl.
	 *
	 * @param borrower_Loan_Id the borrower_ loan_ ID of this temp bl
	 */
	public void setBorrower_Loan_Id(long borrower_Loan_Id);

	/**
	 * Returns the group ID of this temp bl.
	 *
	 * @return the group ID of this temp bl
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this temp bl.
	 *
	 * @param groupId the group ID of this temp bl
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this temp bl.
	 *
	 * @return the company ID of this temp bl
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this temp bl.
	 *
	 * @param companyId the company ID of this temp bl
	 */
	public void setCompanyId(long companyId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempBl tempBl);

	public int hashCode();

	public CacheModel<TempBl> toCacheModel();

	public TempBl toEscapedModel();

	public String toString();

	public String toXmlString();
}